name: Daily HELB Scraper

on:
  schedule:
    - cron: '0 3 * * *'   # every day at 03:00 UTC
  workflow_dispatch:     # allows manual run from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gnews pandas nltk gspread gspread_dataframe oauth2client

      - name: Ensure NLTK data (vader_lexicon)
        run: |
          python -m nltk.downloader vader_lexicon

      # Method A: write JSON from plain secret (works if you stored raw JSON)
      - name: Write service account JSON (from secret)
        env:
          SA_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          printf '%s' "$SA_JSON" > service_account.json
          ls -l service_account.json

      # If you instead stored a base64-encoded secret, use this step instead:
      # - name: Write service account JSON (from base64 secret)
      #   run: |
      #     echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | base64 --decode > service_account.json
      #     ls -l service_account.json

      - name: Run scraper
        run: python scraper_to_sheets.py
